node:
  restart: always
  build: .
  links:
  - mongo
  - redis
  ports:
  - "8080:8080"
  environment:
  - NODE_ENV=production
mongo:
  image: mongo
  ports:
  - "27017:27017"
redis:
  image: redis
  ports:
  - "6379:6379"
nginxproxy:
  image: jwilder/nginx-proxy
  #environment:
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
  - "80:80"
